version: '3.9'

services:
  # app:
  #   container_name: app
  #   image: 'docker-spring-boot-postgres:latest'
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - DATABASE_URL=jdbc:postgresql://db:5432/postgres
  #     - DATABASE_USERNAME=postgres
  #     - DATABASE_PASSWORD=postgres
  #   depends_on:
  #     - db
  db:
    container_name: db
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
